### ISSUE TITLE
Editor UI

### ISSUE THREAD

**Issue by craftablescience** [craftablescience/ChiraEngine#2]
The main view should have:
- [x] Edit View (edit a world)
- [ ] Game View (play the game)
- [ ] Code View (edit scripts)

Additional windows:
- [ ] Resource Viewer
- [x] Docked Console
- [x] Entity Tree
- [x] Inspector
- [ ] ...and more that I haven't thought of yet

**Comment by ashifolfi** [comment]
Code View shall be implemented using the suggestion in #29

**Comment by ashifolfi** [comment]
![image](https://user-images.githubusercontent.com/29577987/192166269-d0e7dd70-1524-40b0-a277-beb602e61737.png)

had to use ImGuiColorTextEdit instead of Zep due to Zep being seemingly straight up incompatible with our setup but we now have a basic script editor implementation. no anglescript syntax highlighting at the moment but it shouldn't be too difficult to implement

**Comment by ashifolfi** [comment]
The resource browser just needs to have it's crashing issue fixed and a few more things implemented

- [ ] Texture thumbnails
- [ ] Image thumbnails
- [ ] make the icons functional
- [ ] drag and drop to editor windows and from outside sources in
- [ ] fix the sub directory crash issue

**Comment by ashifolfi** [comment]
the code editor is mostly done. pretty much being fully implemented aside from:

- [ ] functional open, new, save buttons
- [ ] AngelScript highlighting
- [ ] Multi file support

**Comment by ashifolfi** [comment]
as for the entity outliner?
I still need to figure out how to make a proper tree system in ImGui for that one

**Comment by ashifolfi** [comment]
progress will be tracked via the pr. do not expect those checkboxes here to be filled out in time with the pr

**Comment by craftablescience** [comment]
Closing in favor of #51
